### ISSUE TITLE
Not working on Chrome

### ISSUE THREAD

**Issue by michaelhaggerty** [adam-team/retell-frontend-reactjs-demo#2]
Ran:
```
npm install
npm start
```

Got error after clicking "Start" on the initial page
```
Uncaught runtime errors:
×
ERROR
TypeError: Failed to fetch
    at registerCall (http://localhost:3002/static/js/bundle.js:94:13)
    at async toggleConversation (http://localhost:3002/static/js/bundle.js:64:36)
```
Chrome Version 120.0.6099.199 (Official Build) (x86_64)

**Comment by keithschacht** [comment]
See the PR which fixes this ^
